export interface Bank {
  bankName: string;
  bankCode: string;
}
const banks: Bank[] = [
  { bankCode: '001', bankName: '한국은행' },
  { bankCode: '002', bankName: '산업은행' },
  { bankCode: '003', bankName: '기업은행' },
  { bankCode: '004', bankName: 'KB국민은행' },
  { bankCode: '005', bankName: '하나은행' },
  { bankCode: '045', bankName: '새마을금고' },
  { bankCode: '007', bankName: '수협은행' },
  { bankCode: '047', bankName: '신협' },
  { bankCode: '010', bankName: 'NH농협은행' },
  { bankCode: '050', bankName: '저축은행' },
  { bankCode: '012', bankName: '농축협' },
  { bankCode: '020', bankName: '우리은행' },
  { bankCode: '021', bankName: '신한은행' },
  { bankCode: '023', bankName: 'SC제일은행' },
  { bankCode: '064', bankName: '산림조합중앙회' },
  { bankCode: '027', bankName: '한국씨티은행' },
  { bankCode: '031', bankName: '대구은행' },
  { bankCode: '071', bankName: '우체국' },
  { bankCode: '032', bankName: '부산은행' },
  { bankCode: '034', bankName: '광주은행' },
  { bankCode: '035', bankName: '제주은행' },
  { bankCode: '037', bankName: '전북은행' },
  { bankCode: '039', bankName: '경남은행' },
  { bankCode: '089', bankName: '케이뱅크' },
  { bankCode: '090', bankName: '카카오뱅크' },
  { bankCode: '092', bankName: '토스혁신준비법인' },
  { bankCode: '102', bankName: '대신저축은행' },
  { bankCode: '103', bankName: '에스비아이저축은행' },
  { bankCode: '104', bankName: '에이치케이저축은행' },
  { bankCode: '105', bankName: '웰컴저축은행' },
  { bankCode: '106', bankName: '신한저축은행' },
  { bankCode: '052', bankName: '모간스탠리은행' },
  { bankCode: '054', bankName: 'HSBC은행' },
  { bankCode: '055', bankName: '도이치은행' },
  { bankCode: '057', bankName: '제이피모간체이스은행' },
  { bankCode: '058', bankName: '미즈호은행' },
  { bankCode: '059', bankName: '엠유에프지은행' },
  { bankCode: '060', bankName: 'BOA은행' },
  { bankCode: '061', bankName: '비엔피파리바은행' },
  { bankCode: '062', bankName: '중국공상은행' },
  { bankCode: '063', bankName: '중국은행' },
  { bankCode: '065', bankName: '대화은행' },
  { bankCode: '066', bankName: '교통은행' },
  { bankCode: '067', bankName: '중국건설은행' },
];

export default banks;
