name: Push To Docker

on:
  push:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        node-version: [12.x]

    runs-on: ubuntu-latest

    # This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
    # For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Cache yarn dependencies
        uses: actions/cache@v1
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build with webpack (with Dependencies Installing)
        env:
          REACT_APP_PRODUCTION_API_HOSTNAME: ${{ secrets.REACT_APP_PRODUCTION_API_HOSTNAME }}
          REACT_APP_PRODUCTION_REACT_HOSTNAME: ${{ secrets.REACT_APP_PRODUCTION_REACT_HOSTNAME }}
          REACT_APP_GOOGLE_MAP_API_KEY: ${{ secrets.REACT_APP_GOOGLE_MAP_API_KEY }}
        run: |
          cd client-ts
          yarn install
          yarn build
          cd ..
          cd server
          yarn install
          yarn build
          cd ..
          cd socket
          yarn install
          yarn build

      - name: <client-ts> Dockerize and Push to docker hub
        uses: elgohr/Publish-Docker-Github-Action@2.14
        with:
          name: hwasurr/onad_web
          workdir: client-ts
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,1.${{ github.run_number }}"

      - name: <server> Dockerize and Push to docker hub
        uses: elgohr/Publish-Docker-Github-Action@2.14
        with:
          name: hwasurr/onad_web_api
          workdir: server
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,1.${{ github.run_number }}"

      - name: <calculator> Dockerize and Push to docker hub
        uses: elgohr/Publish-Docker-Github-Action@2.14
        with:
          name: hwasurr/onad_calculator
          workdir: calculator
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,1.${{ github.run_number }}"

      - name: <Ad broad socket server> Dockerize and Push to docker hub
        uses: elgohr/Publish-Docker-Github-Action@2.14
        with:
          name: hwasurr/onad_socket
          workdir: socket
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,1.${{ github.run_number }}"

      - name: notify to slack
        uses: 8398a7/action-slack@v2.7.0
        with:
          status: ${{ job.status }}
          author_name: OnAD Web deploy status
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
